### ISSUE TITLE
Unexpected character encoding

### ISSUE THREAD

**Issue by lundvall** [ivahaev/amigo#12]
If, for example, a messages contains the non-ASCII characters `ö`, that character will be replaced by the replacement character � .

[Go Playground](https://play.golang.org/p/Mk8EHYywJa)

One way to handle this is to repack the read bytes as `rune`s in [readMessage(...)](https://github.com/ivahaev/amigo/blob/master/ami.go#L234-L238). I'm happy to create a PR for this.

**Comment by ivahaev** [comment]
Ok, waiting for your PR.

**Comment by ivahaev** [comment]
Can you provide sample message with non-ASCII characters that decoded incorrectly?

**Comment by lundvall** [comment]
I have this problem, for example, when receiving [AgentConnect](https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+ManagerEvent_AgentConnect) and the `ConnectedLineName/DestConnectedLineName` contains a character like the one in the [test](https://github.com/ivahaev/amigo/pull/13/commits/0e84c0e1399a7b76d8b964e73230b94b51b9d512#diff-efe1d5268124002a36b576012479a843R103).

A sample message is provided in the [test](https://github.com/ivahaev/amigo/pull/13/commits/0e84c0e1399a7b76d8b964e73230b94b51b9d512#diff-efe1d5268124002a36b576012479a843R103) with the message `Astérix` as a sequence of bytes, as it would be correctly encoded if I were to provide a string.

The current result of [readMessage(...)](https://github.com/ivahaev/amigo/blob/master/ami.go#L234) is `Ast�rix`, `string(message) => 
 Ast�rix` and after `toUnicode(...)` it is `Astérix`.

**Comment by ivahaev** [comment]
Please, full message from asterisk. I use Amigo in Russian projects and I have no problem with non-ASCII symbols. I want to see full message, because it should parse correctly.

**Comment by lundvall** [comment]
When capturing traffic for this issue it seems that the problem are local to some hosts. I will close this issue and dig deeper.
