### ISSUE TITLE
Multiconnect to several Asterisk Host

### ISSUE THREAD

**Issue by beho1der** [ivahaev/amigo#16]
I use you library, it's good library. I have the task of connecting to several asterisk, it's work this code

> for _, s := range conf.Asterisk {
		settings := &amigo.Settings{Username: s.Login, Password: s.Password, Host: s.IP, Port: s.Port}
		a := amigo.New(settings)
		a.Connect()
		a.On("connect", func(message string) {
			fmt.Println("Connected", message)
		})
		a.On("error", func(message string) {
			fmt.Println("Connection error:", message)
		})
		a.RegisterHandler("DialBegin", DialBeginHandler)
		a.RegisterHandler("BridgeEnter", BridgeEnterHandler)
		a.RegisterHandler("Newchannel", NewchanneHandler)
	}

But  when the event handler is work, I can not determine from which PBX the event came, is it possible  expand the library to work with several PBXs or can you advise the solution?

**Comment by ivahaev** [comment]
I think, need to add **ConnectionID** field to **Settings** and append it into every event. What do you think?

Also you can to do it in your code.

**Comment by beho1der** [comment]
It would be great, but can enough append it into every event - Settings.Host, usually this is unique value.

**Comment by ivahaev** [comment]
You can do such this:
```go
func DialBeginHandler(id int) func (map[string]string) {
	return func(e map[string]string) {
		// handling event and connection id
	}
}

func main() {
	for i, s := range conf.Asterisk {
		settings := &amigo.Settings{Username: s.Login, Password: s.Password, Host: s.IP, Port: s.Port}
		a := amigo.New(settings)
		a.Connect()

		a.RegisterHandler("DialBegin", DialBeginHandler(i))
	}
}

```

Now in handler you can handle additional info — connection id. You can pass host, port or any other necessary info.

**Comment by ivahaev** [comment]
I think, it's enough to solve you task and no need to update amigo.

**Comment by beho1der** [comment]
YES, this is a great solution, add to the examples

**Comment by beho1der** [comment]
Thank you very much for your help, translating the old project into golang, at the same time I'm studying the language
