### ISSUE TITLE
Setting an event's "Time" received overwrites the "Time" field in some events

### ISSUE THREAD

**Issue by davidkus** [ivahaev/amigo#20]
When an event is received by amigo, looks like the time that the event is received is being set in the "Time" field. However, this overwrites some values that are expected in the event. Specifically, the "Time" value sent in PeerStatus events: https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+ManagerEvent_PeerStatus

https://github.com/ivahaev/amigo/blob/dc432217d75a518d394120941165b5eda838eb0d/ami.go#L396

**Comment by ivahaev** [comment]
Thank you for finding this issue. I think, the best way to eliminate it is rename `Time` key to another. For example `AmigoTime`.
