### ISSUE TITLE
Disconnect function

### ISSUE THREAD

**Issue by aerosales10** [ivahaev/amigo#22]
Hi @ivahaev, excelent lib, thanks. This is a feature request. It would be great if an amigo.Disconnect() function exists. I have a pool of connections and I need to connect and disconnect on demand.

**Comment by ivahaev** [comment]
Hi, Alberto, thank you for words :)
I haven't free time to develop new features for this lib, but you can do it by yourself and create PR. Or you can wait 🤷🏼‍♂️

**Comment by ivahaev** [comment]
Plz, look at this PR :)
https://github.com/ivahaev/amigo/pull/23
