### ISSUE TITLE
Not connecting to the AMI Server

### ISSUE THREAD

**Issue by iliesh** [ivahaev/amigo#29]
Hello,

Trying to use this library but a.Connect doesn't work for me. 

This is the code I'm trying to use:

```
        fmt.Println("Init Amigo")
        settings := &amigo.Settings{Username: "admin", Password: "admin123", Host: "127.0.0.1:5038"}
	a := amigo.New(settings)
	a.Connect()

	// Listen for connection events
	a.On("connect", func(message string) {
		fmt.Println("Connected", message)
	})
	a.On("error", func(message string) {
		fmt.Println("Connection error:", message)
	})

	// Registering default handler function for all events.
	a.RegisterDefaultHandler(DefaultHandler)
```

But, I'm getting only "Init Amigo" and the application is exiting with status code 0. Also, I noticed that the same happens when application is not able to connect to the server, while I expected to get an error message. In doc is saying that if the application cannot reach the server - it will try again on every second, which is not happening in my case. Basically I need to connect to the server and listen for all events coming from there, could you please tell me what I'm doing wrong?

Go ver: go version go1.16.4
Module version: github.com/ivahaev/amigo v0.1.11-0.20210303101006-9e0ec2c34445

**Comment by iliesh** [comment]
Figured it out, didn't pay attention to the last 2 lines from the example.

**Comment by mariemec** [comment]
Why do those 2 lines matter? Mind explaining it to me, I'm having the same issue

**Comment by ivahaev** [comment]
> Why do those 2 lines matter? Mind explaining it to me, I'm having the same issue

Because without this two lines your application will stop working. This lines means forever loop, so your app can receive and handle AMI envets.
