### ISSUE TITLE
Response data missing for 'Action: Command'

### ISSUE THREAD

**Issue by ccstanley** [ivahaev/amigo#3]
I need to issue a Command Action though AMI. Basically I could pass any command string accepted in Asterisk CLI to 'Command:' field. 

The problem is response from asterisk is not in a standard 'Field:Value' format. It is something like this:
```
Action: Command
Command: core show hi

Response: Follows
Privilege: Command
No such command 'core show hi' (type 'core show help core show hin' for other possible commands)
--END COMMAND--
```

amigo seems does not recognize the response string and it ignores the response body:
```
res, _ := ami.Action(map[string]string{
     "Action":  "Command",
     "Command": "core show hi",
 })
 // res == {"Response":"Follows","Privilege":"Command"}
```

Can we introduce a CommandAction specifically for that? Or offer an option to return the raw response body?

Thanks!

**Comment by ivahaev** [comment]
Hi,
I need to make some tests before.

**Comment by ivahaev** [comment]
Fixed in 
6457081ea3101500da68ce5ee6060a1d2f8a3dec
9c1dbdf4ce0a39b8f7f4dcd83167750ada0b1a8d
