### ISSUE TITLE
cannot use DeviceStateChangeHandler (type func(amigo.M)) as type amigo.handlerFunc in argument to a.RegisterHandler

### ISSUE THREAD

**Issue by webdev4u** [ivahaev/amigo#4]
go version go1.7.3 windows/amd64
Взял код с гитхаба, при компиляции выдает ошибку
cannot use DeviceStateChangeHandler (type func(amigo.M)) as type amigo.handlerFunc in argument to a.RegisterHandler

**Comment by ivahaev** [comment]
Да, проблему понял. Несколько менял API и перестарался

**Comment by ivahaev** [comment]
Исправлено. И пример тоже исправлен.

**Comment by webdev4u** [comment]
Спасибо, заработало.
