### ISSUE TITLE
Possible error in ami.go

### ISSUE THREAD

**Issue by alodr** [ivahaev/amigo#5]
I found that Amigo works wrong if a value in Event is empty - all followed Events are parsed as one.
It can be reproduced with PJSIPShowEndpoints command:

Action: PJSIPShowEndpoints

Response: Success
EventList: start
Message: A listing of Endpoints follows, presented as EndpointList events

Event: EndpointList
ObjectType: endpoint
ObjectName: XXXXX
Transport: transport-udp
Aor: XXX
Auths:
OutboundAuths:
Contacts: XXXX/sip:XXXX,
DeviceState: Unavailable
**ActiveChannels:**

I think the problem is in the file ami.go line 191:
**if len(value) > 0 {**
	chanOut <- data
        data = make(map[string]string)
}
Thank you!

**Comment by ivahaev** [comment]
Fixed in 6457081ea3101500da68ce5ee6060a1d2f8a3dec
