### ISSUE TITLE
Timeout in command's long response

### ISSUE THREAD

**Issue by alodr** [ivahaev/amigo#9]
Function readMessage in ami.go takes "ActionID" pair in command's long response as part of this response so result of Action function is Error:Timeout.
Possible solution is to replace ami.go:254 `if responseFollows && key != "Privilege" {` to `if responseFollows && key != "Privilege" && key != "ActionID" {`

Thank you

**Comment by ivahaev** [comment]
Please, provide more detailed example, which event parsed with error?

**Comment by alodr** [comment]
In go:
`result, err := a.Action(map[string]string{"Action": "Command", "Command": "core show version"})
fmt.Println(result, err)`

In the console: 
`map[Error:Timeout] <nil>`

_Request:_
Action: Command\n
Command: core show version\n
ActionID: bd7c1246-10cf-428e-8ccb-787c2292e60b\n
\n

_Response:_
Response: Follows\r\n
Privilege: Command\r\n

Response data:
ActionID: bd7c1246-10cf-428e-8ccb-787c2292e60b\r\n
Asterisk 13.14.0 built by root @ ast-node2a on a x86_64 running Linux on 2017-02-14 06:06:59 UTC\n
--END COMMAND--\r\n
\r\n
